### PR TITLE
remove duplicate code which is already defined at global level

### PR DESCRIPTION
**Pull request by pratik3558**

### CODE REVIEW

**Comment by pratik3558** [comment]
@liyucheng09 this removes duplicate code which is already defined at global level

**Comment by pratik3558** [comment]
@liyucheng09 could you review the code whenever you get a chance, please? These are minor enhancements and some duplicate code removal

**Comment by pratik3558** [comment]
@liyucheng09 just following up to see if you can review the code whenever you get a chance, please?

**Review by liyucheng09 — APPROVED** [review]
Good changes. Approved.

**Pull request merged**
